INSERT INTO `newapi`.`models` (`id`, `model_name`, `description`, `icon`, `tags`, `vendor_id`, `endpoints`, `status`, `sync_official`, `created_time`, `updated_time`, `deleted_at`, `name_rule`) VALUES (1, 'gpt-image-2', 'OpenAI GPT-Image-2 图像生成模型', '', 'image,generation', 1, '', 1, 1, 1782191008, 1782191008, NULL, 0);
INSERT INTO `newapi`.`models` (`id`, `model_name`, `description`, `icon`, `tags`, `vendor_id`, `endpoints`, `status`, `sync_official`, `created_time`, `updated_time`, `deleted_at`, `name_rule`) VALUES (2, 'gpt-image-1', 'OpenAI GPT-Image-1 图像生成模型', '', 'image,generation', 1, '', 1, 1, 1782191018, 1782191018, NULL, 0);
INSERT INTO `newapi`.`models` (`id`, `model_name`, `description`, `icon`, `tags`, `vendor_id`, `endpoints`, `status`, `sync_official`, `created_time`, `updated_time`, `deleted_at`, `name_rule`) VALUES (4, 'agnes-image-2.1-flash', 'Agnes AI 图像生成模型', '', 'image,generation', 1, '/images/generations', 1, 0, 1782233186, 1782233186, NULL, 0);


INSERT INTO `newapi`.`channels` (`id`, `type`, `key`, `open_ai_organization`, `test_model`, `status`, `name`, `weight`, `created_time`, `test_time`, `response_time`, `base_url`, `other`, `balance`, `balance_updated_time`, `models`, `group`, `used_quota`, `model_mapping`, `status_code_mapping`, `priority`, `auto_ban`, `other_info`, `tag`, `setting`, `param_override`, `header_override`, `remark`, `channel_info`, `settings`) VALUES (1, 1, 'sk-test-key-placeholder', NULL, NULL, 1, '测试图片生成渠道', 100, 1782192649, 1782192649, NULL, 'https://api.openai.com/v1', NULL, NULL, NULL, 'gpt-image-2,gpt-image-1', 'default', 0, NULL, '', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `newapi`.`channels` (`id`, `type`, `key`, `open_ai_organization`, `test_model`, `status`, `name`, `weight`, `created_time`, `test_time`, `response_time`, `base_url`, `other`, `balance`, `balance_updated_time`, `models`, `group`, `used_quota`, `model_mapping`, `status_code_mapping`, `priority`, `auto_ban`, `other_info`, `tag`, `setting`, `param_override`, `header_override`, `remark`, `channel_info`, `settings`) VALUES (2, 1, 'sk-XLjUamxpyqqWLpB58KlpUDgL7GmTnnHmhD09hqq61hULY0Lc', NULL, NULL, 1, 'Agnes AI Image', 0, 1782233209, NULL, NULL, 'https://apihub.agnes-ai.com/v1', NULL, NULL, NULL, 'agnes-image-2.1-flash', 'default', 0, NULL, '', 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO `newapi`.`users` (`id`, `username`, `password`, `display_name`, `role`, `status`, `email`, `github_id`, `discord_id`, `oidc_id`, `wechat_id`, `telegram_id`, `access_token`, `quota`, `used_quota`, `request_count`, `group`, `aff_code`, `aff_count`, `aff_quota`, `aff_history`, `inviter_id`, `deleted_at`, `linux_do_id`, `setting`, `remark`, `stripe_customer`, `created_at`, `last_login_at`) VALUES (3, 'root', '$2a$10$u5dqap8CKo5ZYmgxX.rdU..nR.EK.nsJYfXNEbz.yQnPz/Ea3Z9Aa', 'root', 1, 1, '', '', '', '', '', '', NULL, 50000000, 0, 0, 'default', 'FMce', 0, 0, 0, 0, NULL, '', '{\"gotify_priority\":0,\"sidebar_modules\":\"{\\\"chat\\\":{\\\"chat\\\":true,\\\"enabled\\\":true,\\\"playground\\\":true},\\\"console\\\":{\\\"detail\\\":true,\\\"enabled\\\":true,\\\"log\\\":true,\\\"midjourney\\\":true,\\\"task\\\":true,\\\"token\\\":true},\\\"personal\\\":{\\\"enabled\\\":true,\\\"personal\\\":true,\\\"topup\\\":true}}\"}', '', '', 1782143884, 1782230930);
INSERT INTO `newapi`.`users` (`id`, `username`, `password`, `display_name`, `role`, `status`, `email`, `github_id`, `discord_id`, `oidc_id`, `wechat_id`, `telegram_id`, `access_token`, `quota`, `used_quota`, `request_count`, `group`, `aff_code`, `aff_count`, `aff_quota`, `aff_history`, `inviter_id`, `deleted_at`, `linux_do_id`, `setting`, `remark`, `stripe_customer`, `created_at`, `last_login_at`) VALUES (4, 'root123', '$2a$10$YBXEWpimqlLMzU/iQy8YouF6wOUyiG15F4ykVzE2Cu70FVkkDA2K.', 'root123', 1, 1, '', '', '', '', '', '', NULL, 0, 0, 0, 'default', 'UVze', 0, 0, 0, 0, NULL, '', '{\"gotify_priority\":0,\"sidebar_modules\":\"{\\\"chat\\\":{\\\"chat\\\":true,\\\"enabled\\\":true,\\\"playground\\\":true},\\\"console\\\":{\\\"detail\\\":true,\\\"enabled\\\":true,\\\"log\\\":true,\\\"midjourney\\\":true,\\\"task\\\":true,\\\"token\\\":true},\\\"personal\\\":{\\\"enabled\\\":true,\\\"personal\\\":true,\\\"topup\\\":true}}\"}', '', '', 1782143912, 1782144046);



INSERT INTO `newapi`.`options` (`key`, `value`) VALUES ('ModelPrice', '{\"agnes-image-2.1-flash\":0.04}');
